technews/core/urls.py
from django.urls import path
from core import views
# from apps.core.views import signup


#TEMPLATE TAGGING
app_name = 'core'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
]

technews/story/urls.py
from django.urls import path
from story import views

#TEMPLATE TAGGING
app_name = 'story'

urlpatterns = [
    path('submit/', views.submit, name='submit'),
    path('newest/', views.newest, name='newest'),
    path('s/<int:story_id>/vote/', views.vote, name='vote'),
    path('s/<int:story_id>/', views.story, name='story'),
    path('search/', views.search, name='search'),

]

technews/technews/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views
from django.conf.urls import include, url
from django.conf import settings

from core import views as cviews
from story import views as sviews

# from apps.core.views import signup

urlpatterns = [

    # path('signup/', signup, name='signup'),
    path('admin/', admin.site.urls),

    path('core/',include('core.urls')),
    path('story/',include('story.urls')),
    path('userprofile/',include('userprofile.urls')),

    # path('', cviews.index, name='index'),
    path('', sviews.frontpage, name='frontpage'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    # path('signup/', cviews.signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

technews/userprofile/urls.py
from django.urls import path
from userprofile import views

#TEMPLATE TAGGING
app_name = 'userprofile'

urlpatterns = [
    # path('submit/', views.submit, name='submit'),
    # path('newest/', views.newest, name='newest'),
    # path('s/<int:story_id>/vote/', views.vote, name='vote'),
    # path('s/<int:story_id>/', views.story, name='story'),
    path('<str:username>/', views.userprofile, name='userprofile'),
    path('<str:username>/votes/', views.votes, name='votes'),
    path('<str:username>/submissions/', views.submissions, name='submissions'),

]

technews/core/models.py
from django.db import models

# Create your models here.

technews/story/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Story(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()

    number_of_votes = models.IntegerField(default=1)

    created_by = models.ForeignKey(User, related_name='stories', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return '%s' % self.title

class Vote(models.Model):
    story = models.ForeignKey(Story, related_name='votes', on_delete=models.CASCADE)

    created_by = models.ForeignKey(User, related_name='votes', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.story.number_of_votes = self.story.number_of_votes + 1
        self.story.save()

        super(Vote, self).save(*args, **kwargs)

class Comment(models.Model):
    story = models.ForeignKey(Story, related_name='comments', on_delete=models.CASCADE)

    body = models.TextField()

    created_by = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

technews/userprofile/models.py
from django.db import models

# Create your models here.

technews/story/forms.py
from django import forms

from .models import Story, Comment

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ('title', 'url')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

technews/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

# def index(request):
#     return render(request, 'core/index.html')

def signup(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            # console.log("will register user!")
            user = form.save()
            login(request, user)

            return redirect('frontpage')

    else:
        form = UserCreationForm()

    return render(request, 'core/signup.html', {'form':form})

technews/story/views.py
import datetime
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import StoryForm, CommentForm
from .models import Story, Vote, Comment

# Create your views here.
def frontpage(request):
    date_from = datetime.datetime.now(tz=timezone.utc) - datetime.timedelta(days=10)

    stories = Story.objects.filter(created_at__gte=date_from).order_by('-number_of_votes')[0:30]

    return render(request, 'story/frontpage.html', {'stories':stories})

def search(request):
    query = request.GET.get('query', '')

    if len(query)>0:
        stories = Story.objects.filter(title__icontains=query)
    else:
        # stories = []
        date_from = datetime.datetime.now(tz=timezone.utc) - datetime.timedelta(days=10)
        stories = Story.objects.filter(created_at__gte=date_from).order_by('-number_of_votes')[0:30]
        return render(request, 'story/frontpage.html', {'stories':stories})

    return render(request, 'story/search.html', {"stories":stories, "query":query})

def story(request, story_id):
    story = get_object_or_404(Story, pk=story_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.story = story
            comment.created_by = request.user
            comment.save()

            return redirect('story:story', story_id=story_id)
    else:
        form = CommentForm()

    return render(request, 'story/detail.html', {'story':story, 'form':form})

def newest(request):
    stories = Story.objects.all()[0:200]

    return render(request, 'story/newest.html', {'stories':stories})

@login_required
def vote(request, story_id):
    story = get_object_or_404(Story, pk=story_id)

    next_page = request.GET.get('next_page', '')

    if story.created_by != request.user and not Vote.objects.filter(created_by=request.user, story=story):
        vote = Vote.objects.create(story=story, created_by=request.user)

    if next_page == 'story':
        return redirect('story:story', story_id=story_id)
    else:
        return redirect('frontpage')

@login_required
def submit(request):
    if request.method=='POST':
        form = StoryForm(request.POST)

        if form.is_valid():
            story = form.save(commit=False)
            story.created_by = request.user
            story.save()

            return redirect('frontpage')
    else:
        form = StoryForm()

    return render(request, 'story/submit.html', {'form':form})

technews/userprofile/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User

# Create your views here.

def userprofile(request, username):
    user = get_object_or_404(User, username=username)

    number_of_votes = 0

    for story in user.stories.all():
        number_of_votes = number_of_votes + (story.number_of_votes - 1)

    return render(request, 'userprofile/userprofile.html', {"user":user, "number_of_votes":number_of_votes})

def votes(request, username):
    user = get_object_or_404(User, username=username)
    votes = user.votes.all()

    stories = []

    for vote in votes:
        stories.append(vote.story)

    return render(request, 'userprofile/votes.html', {"user":user, "stories":stories})

def submissions(request, username):
    user = get_object_or_404(User, username=username)
    stories = user.stories.all()

    # stories = []
    # 
    # for vote in votes:
    #     stories.append(vote.story)

    return render(request, 'userprofile/submissions.html', {"user":user, "stories":stories})

technews/templates/core/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tech News</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
  </head>
  <body>

    <nav class="navbar is-dark">
      <div class="navbar-brand">
        <a href="/" class="navbar-item"> <strong>Tech News</strong> </a>
      </div>

      <div class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item">
            <form class="" method="GET" action="{% url 'story:search' %}">
              <div class="field has-addons">
                <div class="control">
                  <input type="text" class="input" placeholder="Search..." name="query" value="">
                </div>
                <div class="control">
                  <button class="button is-success">Search</button>
                </div>
              </div>
            </form>
          </div>

        </div>
        <div class="navbar-end">
          <a href="{% url 'story:newest' %}" class="navbar-item">Newest</a>
          <a href="{% url 'story:submit' %}" class="navbar-item">Submit</a>
          <div class="navbar-item">
            <div class="buttons">
              {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="button is-danger"> <strong>Logout</strong> </a>
              {% else %}
                <a href="{% url 'login' %}" class="button is-light"> <strong>Login</strong> </a>
                <a href="{% url 'core:signup' %}" class="button is-success"> <strong>Sign up</strong> </a>
              {% endif %}
            </div>
          </div>
        </div>

      </div>
    </nav>

    <section class="section">
      {% block content %}

      {% endblock %}
    </section>

  </body>
</html>

technews/templates/core/index.html
<!-- you may delete this file -->

{% extends "core/base.html" %}

{% block content %}

  <div class="jumbotron">
    <h1>Tech News</h1>
  </div>

{% endblock %}

technews/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">

    <div class="columns">
      <div class="column is-12">
        <h1 class="title">Login</h1>
      </div>
    </div>

  <!-- </br> -->
  <!-- </br> -->

    <div class="columns">
      <div class="column is-12">
        <form method="POST" class="" action="{% url 'login' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="field">
            <div class="control">
              <button class="button is-success">Login</button>
            </div>
          </div>
        </form>
      </div>
    </div>

  </div>
{% endblock %}

technews/templates/core/signup.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">

    <div class="columns">
      <div class="column is-12">
        <h1 class="title">Sign up</h1>
      </div>
    </div>

  <!-- </br> -->
  <!-- </br> -->

    <div class="columns">
      <div class="column is-12">
        <form method="POST" class="" action="{% url 'core:signup' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="field">
            <div class="control">
              <button class="button is-success">Sign up</button>
            </div>
          </div>
        </form>
      </div>
    </div>

  </div>
{% endblock %}

technews/templates/story/detail.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <div class="columns">
      <div class="column is-12">
        <h1 class="title">{{ story.title }}</h1>
        <h2 class="subtitle">{{ story.number_of_votes }} votes</h2>

        <strong>By: </strong>  <a href="{% url 'userprofile:userprofile' story.created_by.username %}"> {{ story.created_by.username }} </a> {{ story.created_at|timesince }} ago </br>
        <!-- <strong>By: </strong> {{ story.created_by.username }} {{ story.created_at|timesince }} ago </br> -->
        <strong>Visit: </strong><a href="{{ story.url }}" target="_blank">{{ story.url }}</a>

        <hr>

        {% if not story.created_by == request.user %} <a href="{% url 'story:vote' story.id %}?next_page=story" class="button is-success">Vote</a> {% endif %}

      </div>
    </div>
    <div class="columns">
      <div class="column is-12">
        <hr>

        <h2 class="subtitle">Comments</h2>

        {% for comment in story.comments.all %}
          <article class="media">
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>{{ comment.created_by.username }}</strong> <small>{{ comment.created_at|timesince }} ago</small> <br>
                  {{ comment.body }}
                </p>
              </div>
            </div>
          </article>
        {% empty %}
          <p>No comments yet!</p>
        {% endfor %}

        <hr>

        <h2 class="subtitle">Add Comment</h2>
        {% if request.user.is_authenticated %}
          <form method="POST" action="{% url 'story:story' story.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="field">
              <div class="field">
                <button class="button is-success">Submit</button>
              </div>
            </div>
          </form>
        {% else %}
          <p>Please login to comment</p>
        {% endif %}

      </div>
    </div>
  </div>
{% endblock %}

technews/templates/story/frontpage.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <div class="columns">
      <div class="column is-12">
        <h1 class="title">Welcome to Tech News!</h1>
      </div>
    </div>
    {% include 'story/parts/stories.html' %}
    <!-- <div class="columns">
      <div class="column is-12">
        <table class="table is-striped is-fullwidth">
          <tbody>
            {% for story in stories %}
              <tr>
                <td>{{ forloop.counter }}.</td>
                <td>
                  <a href="{{ story.url }}" target="_blank"> {{ story.title }} </a>
                  <p>
                    {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince}} ago. |
                    {% if not story.created_by == request.user %} <a href="{% url 'story:vote' story.id %}">Vote</a> {% endif %}
                    <a href="{% url 'story:story' story.id %}">Discuss</a>
                  </p>
                </td>
              </tr>

            {% endfor %}
          </tbody>

        </table>
      </div>
    </div> -->
  </div>
{% endblock %}

technews/templates/story/newest.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <div class="columns">
      <div class="column is-12">
        <h1 class="title">Newest stories!</h1>
      </div>
    </div>
    {% include 'story/parts/stories.html' %}
    <!-- <div class="columns">
      <div class="column is-12">
        <table class="table is-striped is-fullwidth">
          <tbody>
            {% for story in stories %}
              <tr>
                <td>{{ forloop.counter }}.</td>
                <td>
                  <a href="{{ story.url }}" target="_blank"> {{ story.title }} </a>
                  <p>
                    {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince}} ago. |
                    {% if not story.created_by == request.user %} <a href="{% url 'story:vote' story.id %}">Vote</a> {% endif %}
                    <a href="{% url 'story:story' story.id %}">Discuss</a>
                  </p>
                </td>
              </tr>

            {% endfor %}
          </tbody>

        </table>
      </div>
    </div> -->
  </div>
{% endblock %}

technews/templates/story/parts/stories.html
<div class="columns">
  <div class="column is-12">
    <table class="table is-striped is-fullwidth">
      <tbody>
        {% for story in stories %}
          <tr>
            <td>{{ forloop.counter }}.</td>
            <td>
              <a href="{{ story.url }}" target="_blank"> {{ story.title }} </a>
              <p>
                {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince}} ago. |
                {% if not story.created_by == request.user %} <a href="{% url 'story:vote' story.id %}">Vote</a> {% endif %}
                <a href="{% url 'story:story' story.id %}">Discuss</a>
              </p>
            </td>
          </tr>

        {% endfor %}
      </tbody>

    </table>
  </div>
</div>

technews/templates/story/search.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <div class="columns">
      <div class="column is-12">
        <h1 class="title">Search results for "{{query}}" :</h1>
        <!-- <h2 class="subtitle"></h2> -->
      </div>
    </div>
    {% include 'story/parts/stories.html' %}
  </div>
{% endblock %}

technews/templates/story/submit.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">

    <div class="columns">
      <div class="column is-12">
        <h1 class="title">New story</h1>
      </div>
    </div>

  <!-- </br> -->
  <!-- </br> -->

    <div class="columns">
      <div class="column is-12">
        <form method="POST" class="" action="{% url 'story:submit' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="field">
            <div class="control">
              <button class="button is-success">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>

  </div>
{% endblock %}

technews/templates/userprofile/submissions.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <div class="columns">
      <div class="column is-12">
        <h1 class="title">Submitted stories</h1>
      </div>
    </div>
    {% include 'story/parts/stories.html' %}
    <!-- <div class="columns">
      <div class="column is-12">
        <table class="table is-striped is-fullwidth">
          <tbody>
            {% for story in stories %}
              <tr>
                <td>{{ forloop.counter }}.</td>
                <td>
                  <a href="{{ story.url }}" target="_blank"> {{ story.title }} </a>
                  <p>
                    {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince}} ago. |
                    {% if not story.created_by == request.user %} <a href="{% url 'story:vote' story.id %}">Vote</a> {% endif %}
                    <a href="{% url 'story:story' story.id %}">Discuss</a>
                  </p>
                </td>
              </tr>

            {% endfor %}
          </tbody>

        </table>
      </div>
    </div> -->
  </div>
{% endblock %}

technews/templates/userprofile/userprofile.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <div class="columns">
      <div class="column is-12">

        <h1 class="title">{{ user.username }}</h1>
        <h2 class="subtitle">{{ number_of_votes }} votes</h2>

        <hr>

        <a href="{% url 'userprofile:submissions' user.username %}">Submissions</a> |
        <a href="{% url 'userprofile:votes' user.username %}">Votes</a>

      </div>
    </div>
  </div>
{% endblock %}

technews/templates/userprofile/votes.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="container">
    <div class="columns">
      <div class="column is-12">
        <h1 class="title">Voted stories</h1>
      </div>
    </div>
    {% include 'story/parts/stories.html' %}
    <!-- <div class="columns">
      <div class="column is-12">
        <table class="table is-striped is-fullwidth">
          <tbody>
            {% for story in stories %}
              <tr>
                <td>{{ forloop.counter }}.</td>
                <td>
                  <a href="{{ story.url }}" target="_blank"> {{ story.title }} </a>
                  <p>
                    {{ story.number_of_votes }} votes by {{ story.created_by.username }} {{ story.created_at|timesince}} ago. |
                    {% if not story.created_by == request.user %} <a href="{% url 'story:vote' story.id %}">Vote</a> {% endif %}
                    <a href="{% url 'story:story' story.id %}">Discuss</a>
                  </p>
                </td>
              </tr>

            {% endfor %}
          </tbody>

        </table>
      </div>
    </div> -->
  </div>
{% endblock %}